/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as WritingsRouteImport } from './app/writings'
import { Route as StoryRouteImport } from './app/story'
import { Route as SpacesRouteImport } from './app/spaces'
import { Route as PromptsRouteImport } from './app/prompts'
import { Route as IndexRouteImport } from './app/index'
import { Route as SpacesIndexRouteImport } from './app/spaces.index'
import { Route as SpacesSlugRouteImport } from './app/spaces.$slug'
import { Route as BlogSlugRouteImport } from './app/blog.$slug'
import { Route as ApiSitemapDotxmlRouteImport } from './app/api.sitemap[.]xml'
import { Route as ApiFeedDotxmlRouteImport } from './app/api.feed[.]xml'
import { Route as ApiTrpcSplatRouteImport } from './app/api.trpc.$'

const WritingsRoute = WritingsRouteImport.update({
  id: '/writings',
  path: '/writings',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesRoute = SpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesIndexRoute = SpacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpacesRoute,
} as any)
const SpacesSlugRoute = SpacesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SpacesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedDotxmlRoute = ApiFeedDotxmlRouteImport.update({
  id: '/api/feed.xml',
  path: '/api/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prompts': typeof PromptsRoute
  '/spaces': typeof SpacesRouteWithChildren
  '/story': typeof StoryRoute
  '/writings': typeof WritingsRoute
  '/api/feed.xml': typeof ApiFeedDotxmlRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/spaces/': typeof SpacesIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prompts': typeof PromptsRoute
  '/story': typeof StoryRoute
  '/writings': typeof WritingsRoute
  '/api/feed.xml': typeof ApiFeedDotxmlRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/spaces': typeof SpacesIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prompts': typeof PromptsRoute
  '/spaces': typeof SpacesRouteWithChildren
  '/story': typeof StoryRoute
  '/writings': typeof WritingsRoute
  '/api/feed.xml': typeof ApiFeedDotxmlRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/spaces/$slug': typeof SpacesSlugRoute
  '/spaces/': typeof SpacesIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prompts'
    | '/spaces'
    | '/story'
    | '/writings'
    | '/api/feed.xml'
    | '/api/sitemap.xml'
    | '/blog/$slug'
    | '/spaces/$slug'
    | '/spaces/'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prompts'
    | '/story'
    | '/writings'
    | '/api/feed.xml'
    | '/api/sitemap.xml'
    | '/blog/$slug'
    | '/spaces/$slug'
    | '/spaces'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/prompts'
    | '/spaces'
    | '/story'
    | '/writings'
    | '/api/feed.xml'
    | '/api/sitemap.xml'
    | '/blog/$slug'
    | '/spaces/$slug'
    | '/spaces/'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PromptsRoute: typeof PromptsRoute
  SpacesRoute: typeof SpacesRouteWithChildren
  StoryRoute: typeof StoryRoute
  WritingsRoute: typeof WritingsRoute
  ApiFeedDotxmlRoute: typeof ApiFeedDotxmlRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writings': {
      id: '/writings'
      path: '/writings'
      fullPath: '/writings'
      preLoaderRoute: typeof WritingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces': {
      id: '/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof SpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/': {
      id: '/spaces/'
      path: '/'
      fullPath: '/spaces/'
      preLoaderRoute: typeof SpacesIndexRouteImport
      parentRoute: typeof SpacesRoute
    }
    '/spaces/$slug': {
      id: '/spaces/$slug'
      path: '/$slug'
      fullPath: '/spaces/$slug'
      preLoaderRoute: typeof SpacesSlugRouteImport
      parentRoute: typeof SpacesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed.xml': {
      id: '/api/feed.xml'
      path: '/api/feed.xml'
      fullPath: '/api/feed.xml'
      preLoaderRoute: typeof ApiFeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SpacesRouteChildren {
  SpacesSlugRoute: typeof SpacesSlugRoute
  SpacesIndexRoute: typeof SpacesIndexRoute
}

const SpacesRouteChildren: SpacesRouteChildren = {
  SpacesSlugRoute: SpacesSlugRoute,
  SpacesIndexRoute: SpacesIndexRoute,
}

const SpacesRouteWithChildren =
  SpacesRoute._addFileChildren(SpacesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PromptsRoute: PromptsRoute,
  SpacesRoute: SpacesRouteWithChildren,
  StoryRoute: StoryRoute,
  WritingsRoute: WritingsRoute,
  ApiFeedDotxmlRoute: ApiFeedDotxmlRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
