/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as StoryRouteImport } from './app/story'
import { Route as PromptsRouteImport } from './app/prompts'
import { Route as ProjectsRouteImport } from './app/projects'
import { Route as ProgramsRouteImport } from './app/programs'
import { Route as PostsRouteImport } from './app/posts'
import { Route as IndexRouteImport } from './app/index'
import { Route as PromptsIndexRouteImport } from './app/prompts.index'
import { Route as ProjectsIndexRouteImport } from './app/projects.index'
import { Route as ProgramsIndexRouteImport } from './app/programs.index'
import { Route as PromptsSlugRouteImport } from './app/prompts.$slug'
import { Route as ProgramsSlugRouteImport } from './app/programs.$slug'
import { Route as BlogSlugRouteImport } from './app/blog.$slug'
import { Route as ApiSitemapDotxmlRouteImport } from './app/api.sitemap[.]xml'
import { Route as ApiFeedDotxmlRouteImport } from './app/api.feed[.]xml'
import { Route as ApiTrpcSplatRouteImport } from './app/api.trpc.$'

const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsIndexRoute = PromptsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PromptsRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramsRoute,
} as any)
const PromptsSlugRoute = PromptsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PromptsRoute,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgramsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedDotxmlRoute = ApiFeedDotxmlRouteImport.update({
  id: '/api/feed.xml',
  path: '/api/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts': typeof PostsRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/prompts': typeof PromptsRouteWithChildren
  '/story': typeof StoryRoute
  '/api/feed.xml': typeof ApiFeedDotxmlRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/prompts/$slug': typeof PromptsSlugRoute
  '/programs/': typeof ProgramsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/prompts/': typeof PromptsIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts': typeof PostsRoute
  '/story': typeof StoryRoute
  '/api/feed.xml': typeof ApiFeedDotxmlRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/prompts/$slug': typeof PromptsSlugRoute
  '/programs': typeof ProgramsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/prompts': typeof PromptsIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/posts': typeof PostsRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/prompts': typeof PromptsRouteWithChildren
  '/story': typeof StoryRoute
  '/api/feed.xml': typeof ApiFeedDotxmlRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/prompts/$slug': typeof PromptsSlugRoute
  '/programs/': typeof ProgramsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/prompts/': typeof PromptsIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts'
    | '/programs'
    | '/projects'
    | '/prompts'
    | '/story'
    | '/api/feed.xml'
    | '/api/sitemap.xml'
    | '/blog/$slug'
    | '/programs/$slug'
    | '/prompts/$slug'
    | '/programs/'
    | '/projects/'
    | '/prompts/'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/posts'
    | '/story'
    | '/api/feed.xml'
    | '/api/sitemap.xml'
    | '/blog/$slug'
    | '/programs/$slug'
    | '/prompts/$slug'
    | '/programs'
    | '/projects'
    | '/prompts'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/posts'
    | '/programs'
    | '/projects'
    | '/prompts'
    | '/story'
    | '/api/feed.xml'
    | '/api/sitemap.xml'
    | '/blog/$slug'
    | '/programs/$slug'
    | '/prompts/$slug'
    | '/programs/'
    | '/projects/'
    | '/prompts/'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsRoute: typeof PostsRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  PromptsRoute: typeof PromptsRouteWithChildren
  StoryRoute: typeof StoryRoute
  ApiFeedDotxmlRoute: typeof ApiFeedDotxmlRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/': {
      id: '/prompts/'
      path: '/'
      fullPath: '/prompts/'
      preLoaderRoute: typeof PromptsIndexRouteImport
      parentRoute: typeof PromptsRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/programs/': {
      id: '/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/prompts/$slug': {
      id: '/prompts/$slug'
      path: '/$slug'
      fullPath: '/prompts/$slug'
      preLoaderRoute: typeof PromptsSlugRouteImport
      parentRoute: typeof PromptsRoute
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed.xml': {
      id: '/api/feed.xml'
      path: '/api/feed.xml'
      fullPath: '/api/feed.xml'
      preLoaderRoute: typeof ApiFeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProgramsRouteChildren {
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsSlugRoute: ProgramsSlugRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface PromptsRouteChildren {
  PromptsSlugRoute: typeof PromptsSlugRoute
  PromptsIndexRoute: typeof PromptsIndexRoute
}

const PromptsRouteChildren: PromptsRouteChildren = {
  PromptsSlugRoute: PromptsSlugRoute,
  PromptsIndexRoute: PromptsIndexRoute,
}

const PromptsRouteWithChildren =
  PromptsRoute._addFileChildren(PromptsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsRoute: PostsRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  PromptsRoute: PromptsRouteWithChildren,
  StoryRoute: StoryRoute,
  ApiFeedDotxmlRoute: ApiFeedDotxmlRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
